- index.html
- style.css
This PR will solve the issue #1 
https://user-images.githubusercontent.com/17003525/193989824-f1ea8c5b-538f-4495-aa98-a0d776dbab1c.mov
> Fix Site move to top issue

- script.js
> Added some sentences

- script.js
I've added 12 sentences of movie dialogues, quotes, idioms and many more to the random sentence generator!
Closes #5
> I've added 12 sentences to be generated at random

- script.js
> Added 12 new quotes/sayings

- index.html
- script.js
- style.css
Description:
Play button in input box is enhanced
Issue: #20 
Screenshot:
> play button enhanced

- script.js
@Subham-Maity  I have added lines 76-85 in the dataset in script.js.
> Added 10  lines to the dataset.

- script.js
> added quotes

- style.css
Fixed the position and cut in the play button.
> update the position and fix the play icon

- dataset.js
> Add 10 inspirational Hollywood movie dialogues 

- index.html
- style.css
I made the following improvements:- 
1. Intro container's display to flex and allign, justify-content to center
2. Edited intro container's paragraph from "Welcome to SOS World" to "Enter the SOS World" to make it more user friendly
> Made intro container's display to flex

- index.html
- style.css
Reverts Subham-Maity/StockOfSentence#42
> Revert "Made intro container's display to flex"

- index.html
- script.js
- style.css
I made intro-container's display to flex and also fixed main random function.
> Made intro-container's display to flex and also fixed main random function not working properly

- dataset.js
I added 10 dialogues from hollywood movies with clear meaning inside dataset
> Add 10 dialogues and quotes from Hollywood movies inside dataset #50

- dataset.js
Added emojis and did the changes as asked.
> Added Hollywood dialogues

- dataset.js
@Subham-Maity Can you please merge this PR
> Added 10 Hollywood Insightful quotes

- dataset.js
Hello sir, I have added ten inspirational quotes from Hollywood movies. Please, approve if you find it okay.
> added 10 quotes from hollyhood movies

- dataset.js
#50 
@Subham-Maity 
you can merge it
> Added 10 dialogues from money heist

- dataset.js
I have added quotes in the dataset.js file. Please merge my PR.
> Added some inspirational and insightful quotes from various Hollywood movies

- dataset.js
> Update dataset - issue #61

- CODE_OF_CONDUCT.md
- README.md
Fixed issue: #72 and added code_of_conduct.md file
> Updated README.md

- dataset.js
Love the project!❤️, I hope I can contribute and that my sentences are correct 😊.
Greetings from México
> Add 10 series and movies quotes

- dataset.js
Hey ! @Subham-Maity added 10 quotes ...kindly check once and review it :)
> 10 quotes added. Kindly review it !

- audioplay.js
- index.html
Fixed issues mentioned in ISSUE #77 
*Bug Fixes :
1. Pause audio when cross (close) button is pressed.
*Feature Added :
1. Added a feature to play pause audio by pressing space bar
> Fixed audio bug & Added a Feature

- dataset.js
> updated dataset.js in accordance with #78

- dataset.js
The issue #78 was looked at. 
I have added 14 new quotes
> added 14 new quotes

- dataset.js
I have created this PR for hacktoberfest '22. I'm new to open source and looking for contributions on projects that interest me. Please consider my PR. Thankyou.
> Added Quotes From one on my fav movies

- audioplay.js
- index.html
- script.js
- style.css
Signed-off-by: Manoj Marmat <manojrajput762000@gmail.com>
Issue:
Adding new Feature #92 
Desc:
when user press space bar or click play button or click close button pop up gets disappear
otherwise pop up will show again
Screenshot:
> Text Show and Disappear Features

- dataset.js
added movie quotes and their meanings with the required emojis
> Added 12 movie quotes in dataset.js

- index.html
The audio file was taken down, and a link to the audio file was replaced; it now functions flawlessly.
> isuue#91 audio file removed and replaced with link

- dataset.js
I have enhanced the list of all-time best and favorite movie quotes.
> Movies quotes and inspiring character from all time best

- dataset.js
Added 12 inspirational quotes, most from Titanic, and made a new PR as requested. #103
> inspirational added again

- dataset.js
Hello, is it possible to receive the Hacktoberfest 2022 accepted label if this is acceptable?  Thank you :)
> Add Les Misérables and 8 ½ quotes

- dataset.js
fixes : #111 
@Subham-Maity kindly merge the PR
> Added more dialogues to the dataset

- dataset.js
please merge my PR as I have added dialogues according to rule
> Added random dialogues

- dataset.js
Added 10 hollywood movie dialogues to resolve #121
> Added 10 dialogues of hollywood movies

- dataset.js
Added 10 new quotes for the issue #121
> Docs: added 10 new quotes

- CONTRIBUTING.md
- dataset.js
Please advise if you would like any changes or modifications.
Closes issue #131
> Contributing

- dataset.js
I choose to add quotes to your data set. As I thought it might be interesting for your audience.
May I ask a favour, and add the "hacktoberfest" and  "hacktoberfest-accepted" label for me?
This issue closes #124
> Additional quotes added to data set
